-- ============================================================================
-- Itzam.ai — AI Opportunity Assessment intake schema
-- Migration 0001 — initial
--
-- Run order:
--   1) Apply this migration in Supabase SQL editor.
--   2) Insert at least one admin into the `admins` table.
--   3) Verify RLS by switching role in the SQL editor.
-- ============================================================================

create extension if not exists "pgcrypto";
create extension if not exists "citext";

-- ----------------------------------------------------------------------------
-- profiles  (mirrors auth.users)
-- ----------------------------------------------------------------------------
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       citext not null unique,
  full_name   text,
  created_at  timestamptz not null default now()
);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, lower(new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_auth_user();

-- ----------------------------------------------------------------------------
-- admins  (allowlist; mirrored to ADMIN_EMAILS env at bootstrap)
-- ----------------------------------------------------------------------------
create table if not exists public.admins (
  email       citext primary key,
  added_at    timestamptz not null default now(),
  added_by    uuid references auth.users(id) on delete set null
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins a
    where a.email = (auth.jwt() ->> 'email')::citext
  );
$$;

-- ----------------------------------------------------------------------------
-- questionnaires
-- ----------------------------------------------------------------------------
create type questionnaire_status as enum (
  'draft', 'sent', 'in_progress', 'completed', 'cancelled'
);

create table if not exists public.questionnaires (
  id                          uuid primary key default gen_random_uuid(),
  client_email                citext not null,
  client_name                 text not null,
  preferred_locale            text not null default 'es' check (preferred_locale in ('es','en')),
  status                      questionnaire_status not null default 'draft',
  assigned_user_id            uuid references public.profiles(id) on delete set null,
  created_by                  uuid not null references public.profiles(id) on delete restrict,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  sent_at                     timestamptz,
  completed_at                timestamptz,
  cancelled_at                timestamptz,
  -- Invite token: only the SHA-256 hex hash is stored.
  invite_token_hash           text,
  invite_token_expires_at     timestamptz,
  invite_token_uses_count     int not null default 0,
  invite_token_max_uses       int not null default 3,
  invite_token_last_used_at   timestamptz,
  -- Reference (not the OTP itself) to the action_link generated by Supabase.
  supabase_action_link        text,
  -- Full plaintext invite URL (admin-only via RLS). Persisted so the dashboard
  -- can display it after page reload; admins copy & email it manually.
  invite_url                  text,
  -- Client root folder (e.g. Clientes/TechSoluciones MX). Created at issue-link time.
  client_folder_url           text,
  -- Per-assessment folder (e.g. Assessment (07/05/2026)). Created at submit time.
  drive_folder_url            text,
  drive_sheet_url             text
);

create index if not exists idx_questionnaires_email on public.questionnaires (client_email);
create index if not exists idx_questionnaires_status on public.questionnaires (status);
create index if not exists idx_questionnaires_assigned on public.questionnaires (assigned_user_id);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_questionnaires_touch on public.questionnaires;
create trigger trg_questionnaires_touch
  before update on public.questionnaires
  for each row execute procedure public.touch_updated_at();

-- ----------------------------------------------------------------------------
-- questions  (per-questionnaire copy; editable until status='sent')
-- ----------------------------------------------------------------------------
create type question_type as enum ('text','single','multi');

create table if not exists public.questions (
  id                uuid primary key default gen_random_uuid(),
  questionnaire_id  uuid not null references public.questionnaires(id) on delete cascade,
  position          int not null,
  block_es          text not null,
  block_en          text not null,
  type              question_type not null,
  label_es          text not null,
  label_en          text not null,
  options           jsonb not null default '[]'::jsonb,
  required          boolean not null default true,
  multiline         boolean not null default false,
  unique (questionnaire_id, position)
);

create index if not exists idx_questions_q on public.questions (questionnaire_id, position);

-- ----------------------------------------------------------------------------
-- answers
-- ----------------------------------------------------------------------------
create table if not exists public.answers (
  id                uuid primary key default gen_random_uuid(),
  questionnaire_id  uuid not null references public.questionnaires(id) on delete cascade,
  question_id       uuid not null references public.questions(id) on delete cascade,
  value             jsonb not null,
  updated_at        timestamptz not null default now(),
  unique (questionnaire_id, question_id)
);

create index if not exists idx_answers_q on public.answers (questionnaire_id);

drop trigger if exists trg_answers_touch on public.answers;
create trigger trg_answers_touch
  before update on public.answers
  for each row execute procedure public.touch_updated_at();

-- ----------------------------------------------------------------------------
-- submission_jobs  (outbox for post-submit integrations)
-- ----------------------------------------------------------------------------
create type job_kind as enum ('client_folder','drive','client_email','admin_email');
create type job_status as enum ('pending','running','succeeded','failed');

create table if not exists public.submission_jobs (
  id                uuid primary key default gen_random_uuid(),
  questionnaire_id  uuid not null references public.questionnaires(id) on delete cascade,
  kind              job_kind not null,
  status            job_status not null default 'pending',
  attempts          int not null default 0,
  max_attempts      int not null default 6,
  next_retry_at     timestamptz not null default now(),
  last_error        text,
  payload           jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (questionnaire_id, kind)
);

create index if not exists idx_jobs_pending on public.submission_jobs (status, next_retry_at);

drop trigger if exists trg_jobs_touch on public.submission_jobs;
create trigger trg_jobs_touch
  before update on public.submission_jobs
  for each row execute procedure public.touch_updated_at();

-- ----------------------------------------------------------------------------
-- audit_log
-- ----------------------------------------------------------------------------
create table if not exists public.audit_log (
  id          bigserial primary key,
  actor_id    uuid,
  actor_email citext,
  action      text not null,
  target_id   text,
  ip          inet,
  user_agent  text,
  metadata    jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists idx_audit_created on public.audit_log (created_at desc);
create index if not exists idx_audit_action on public.audit_log (action);

-- ----------------------------------------------------------------------------
-- rate_limits  (lightweight token bucket / fixed window)
-- ----------------------------------------------------------------------------
create table if not exists public.rate_limits (
  bucket        text not null,
  identifier    text not null,
  window_start  timestamptz not null,
  count         int not null default 0,
  primary key (bucket, identifier, window_start)
);

create or replace function public.rate_limit_hit(
  p_bucket text,
  p_identifier text,
  p_window_seconds int,
  p_limit int
) returns table (allowed boolean, remaining int, reset_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_window_start timestamptz;
  v_count int;
begin
  v_window_start := date_trunc('second', now())
    - (extract(epoch from now())::bigint % p_window_seconds) * interval '1 second';

  insert into public.rate_limits (bucket, identifier, window_start, count)
  values (p_bucket, p_identifier, v_window_start, 1)
  on conflict (bucket, identifier, window_start)
  do update set count = public.rate_limits.count + 1
  returning count into v_count;

  -- Opportunistic GC of old windows for this identifier.
  delete from public.rate_limits
  where bucket = p_bucket
    and identifier = p_identifier
    and window_start < v_window_start - (p_window_seconds * interval '1 second');

  allowed := v_count <= p_limit;
  remaining := greatest(0, p_limit - v_count);
  reset_at := v_window_start + (p_window_seconds * interval '1 second');
  return next;
end;
$$;

-- ============================================================================
-- Row Level Security
-- ============================================================================

alter table public.profiles            enable row level security;
alter table public.admins              enable row level security;
alter table public.questionnaires      enable row level security;
alter table public.questions           enable row level security;
alter table public.answers             enable row level security;
alter table public.submission_jobs     enable row level security;
alter table public.audit_log           enable row level security;
alter table public.rate_limits         enable row level security;

alter table public.profiles            force row level security;
alter table public.questionnaires      force row level security;
alter table public.questions           force row level security;
alter table public.answers             force row level security;

-- profiles: users see their own row; admins see all.
drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles
  for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles
  for update using (id = auth.uid())
  with check (id = auth.uid());

-- admins table: only readable by admins (via service role for is_admin()).
drop policy if exists admins_admin_only on public.admins;
create policy admins_admin_only on public.admins
  for select using (public.is_admin());

-- questionnaires: admin all; client only their assigned ones.
drop policy if exists q_admin_all on public.questionnaires;
create policy q_admin_all on public.questionnaires
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists q_client_select on public.questionnaires;
create policy q_client_select on public.questionnaires
  for select using (
    assigned_user_id = auth.uid()
    and status in ('sent','in_progress','completed')
  );

drop policy if exists q_client_update on public.questionnaires;
create policy q_client_update on public.questionnaires
  for update using (
    assigned_user_id = auth.uid()
    and status in ('sent','in_progress')
  ) with check (
    assigned_user_id = auth.uid()
  );

-- questions: admin all; client read-only for their questionnaires.
drop policy if exists qu_admin_all on public.questions;
create policy qu_admin_all on public.questions
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists qu_client_select on public.questions;
create policy qu_client_select on public.questions
  for select using (
    exists (
      select 1 from public.questionnaires q
      where q.id = questions.questionnaire_id
        and q.assigned_user_id = auth.uid()
        and q.status in ('sent','in_progress','completed')
    )
  );

-- answers: admin read; client CRUD on their own.
drop policy if exists ans_admin_select on public.answers;
create policy ans_admin_select on public.answers
  for select using (public.is_admin());

drop policy if exists ans_client_select on public.answers;
create policy ans_client_select on public.answers
  for select using (
    exists (
      select 1 from public.questionnaires q
      where q.id = answers.questionnaire_id
        and q.assigned_user_id = auth.uid()
    )
  );

drop policy if exists ans_client_insert on public.answers;
create policy ans_client_insert on public.answers
  for insert with check (
    exists (
      select 1 from public.questionnaires q
      where q.id = answers.questionnaire_id
        and q.assigned_user_id = auth.uid()
        and q.status in ('sent','in_progress')
    )
  );

drop policy if exists ans_client_update on public.answers;
create policy ans_client_update on public.answers
  for update using (
    exists (
      select 1 from public.questionnaires q
      where q.id = answers.questionnaire_id
        and q.assigned_user_id = auth.uid()
        and q.status in ('sent','in_progress')
    )
  ) with check (
    exists (
      select 1 from public.questionnaires q
      where q.id = answers.questionnaire_id
        and q.assigned_user_id = auth.uid()
        and q.status in ('sent','in_progress')
    )
  );

-- submission_jobs / audit_log / rate_limits: admin-only via API.
drop policy if exists jobs_admin on public.submission_jobs;
create policy jobs_admin on public.submission_jobs
  for select using (public.is_admin());

drop policy if exists audit_admin on public.audit_log;
create policy audit_admin on public.audit_log
  for select using (public.is_admin());

-- rate_limits: no client access; only service role.
-- (No SELECT/INSERT/UPDATE policies → blocked for authenticated.)
